### PR TITLE
Add abnj attributes

### PR DESCRIPTION
**Pull request by lucacug**
Need some styling fix on the expanded view

### CODE REVIEW

**Comment by WKocur** [comment]
@lucacug Will check this and add the styling now :)

**Comment by WKocur** [comment]
@lucacug ABNK_rel and ABNJ_proj are now options in the themes filter. Should this be the case?

**Comment by lucacug** [comment]
@WKocur  just pushed a fix for that, sorry.

**Comment by WKocur** [comment]
@lucacug Super - I'm happy to merge then! I've added a tiny FE addition, but that just changes the text. Are you happy for me to merge that?

**Comment by lucacug** [comment]
@WKocur yes please go ahead!!

**Pull request merged**
